couchbase1:
  image: chakrar27/couchbase
  volumes:
    - ~/couchbase/node1:/opt/couchbase/var
couchbase2:
  image: chakrar27/couchbase
  volumes:
    - ~/couchbase/node2:/opt/couchbase/var
couchbase3:
  image: chakrar27/couchbase
  volumes:
    - ~/couchbase/node3:/opt/couchbase/var
  ports:
    - 8091:8091
    - 8092:8092 
    - 8093:8093
    - 8094:8094
    - 11210:11210